[uat-webservers]

172.31.31.117 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/key.pem

172.31.16.104 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/key.pem