---
- name: update web and nfs 
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: create folder and file
      file:
        path: /home/ec2-user/tob/bankai
        state: touch
        mode: 0644
        owner: ec2-user
        group: ec2-user
      lineinfile:
        path: /home/ec2-user/tob/bankai
        line: 'KUROSAKI ICHIGO'
        insertbefore: BOF

- name: update LB server and DB server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
